package model;
// Generated Nov 15, 2023 11:45:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Jsf generated by hbm2java
 */
public class Jsf  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private Integer age;
     private String gender;
     private Date doB;

    public Jsf() {
    }

    public Jsf(String firstName, String lastName, Integer age, String gender, Date doB) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.age = age;
       this.gender = gender;
       this.doB = doB;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Date getDoB() {
        return this.doB;
    }
    
    public void setDoB(Date doB) {
        this.doB = doB;
    }




}


